name: note
description: Note is a simple and intuitive Flutter app for managing your everyday notes. Easily jot down your thoughts, ideas, to-do lists, and important information with this user-friendly note-taking application.

publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  logger: ^1.4.0
  intl: ^0.18.0
  dio: ^5.2.0
  shared_preferences: ^2.1.2
  uuid: ^3.0.7
  device_info_plus: ^9.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - l10n/