name: main

on: [push, workflow_dispatch]

jobs:
  analyze:
    name: Run analyzer and formatter
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: dart format --set-exit-if-changed lib/

  test:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          cache: true
      - run: flutter pub get
      - run: flutter test
        id: test
      - if: ${{ failure() && steps.test.conclusion == 'failure' }}
        name: 'Upload test failures'
        uses: actions/upload-artifact@v3
        with:
          name: test-failures
          path: test/failures
          retention-days: 5

  build:
    needs: [ analyze, test ]
    name: Build android on macos
    runs-on: macos-11
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Set up JDK 11
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.10.5
        with:
          java-version: 11
          distribution: temurin
      - name: Create google-services.json
      - run: cat /home/runner/work/note/note/android/app/google-services.json | base64
      - name: Set up google-services.json
      - run: echo ${{ secrets.SERVICES }} > /home/runner/work/note/note/android/app/google-services.json
      - name: Create apk for android
      - run: flutter build apk --dart-define=TOKEN=${{ secrets.TOKEN }} --dart-define=PATH=${{ secrets.PATH }} --dart-define=API_KEY=${{ secrets.API_KEY }} --dart-define=APP_ID=${{ secrets.APP_ID }} --dart-define=MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }} --dart-define=PROJECT_ID=${{ secrets.PROJECT_ID }} --dart-define=STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }}

#  integration-test:
#    runs-on: macos-11
#    timeout-minutes: 25
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup Flutter SDK
#        uses: subosito/flutter-action@v2
#        with:
#          channel: stable
#      - name: Set up JDK 11
#        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.10.5
#        with:
#          java-version: 11
#          distribution: temurin
#      - name: Install Flutter dependencies
#        run: flutter pub get
#      - name: Run unit tests
#        run: flutter test
#      - name: Run integration tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          arch: x86_64
#          profile: Nexus 6
#          script: flutter test integration_test --verbose